export const events = [
  {
    title: "TM30 Academy",
    description: " ",
    id: "faq1",
    date: "March 15, 2022",
    github: "https://github.com/Joshjay05/Tm30-Academy",
    live: "https://tmacademy.tm30.net/",
    organization: "TM30 Global Solutions",
  },
  {
    title: "Teens-Literacy Foundation",
    description: " ",
    id: "faq2",
    date: "October 11, 2023",
    github: "https://github.com/Joshjay05/teens-litereacy",
    live: "https://teensliteracyfoundation.org/",
    organization: "Teens-Literacy Foundation",
  },
  {
    title: "GWC WaitList",
    description: " ",
    id: "faq3",
    date: "June 05, 2023",
    github: "https://github.com/Joshjay05/New-WaitList",
    live: "https://waitlist.gwctechhub.com/",
    organization: "GWCTechSchoolAfrica",
  },
  {
    title: "GWCTechSChoolAfrica Website",
    description: " ",
    id: "faq4",
    date: "June 06 2024",
    github: "https://github.com/Joshjay05/GWC",
    live: "https://gwctechschoolafrica.com/",
    organization: "GWCTechSchoolAfrica",
  },
  {
    title: "TMSaaS Admin-Dashboard",
    description: " ",
    id: "faq5",
    date: "",
    github: "https://github.com/Joshjay05/TmSaas",
    live: "https://tm-saas-28xp.vercel.app/",
    organization: "TM30 Global Solutions",
  },
  // {
  //   title: "GWC-Student Dashboard",
  //   description: " ",
  //   id: "faq6",
  //   date: "Ongoing",
  //   github: "https://github.com/Joshjay05/Student_dashboard",
  //   live: "https://student-dashboard-7sim.vercel.app/",
  //   organization: "GWCTechSchoolAfrica",
  // },
  {
    title: "Everywhere we go Consulting",
    description: "",
    id: "faq7",
    date: "August 1 2024",
    github: "https://github.com/Joshjay05/EduTravels",
    live: "https://www.everywherewegoconsult.org/",
    organization: "Everywhere we go Consulting",
  },
  {
    title: "SHEW Foundation",
    description: "",
    id: "faq8",
    date: "September 10 2024",
    github: "https://github.com/Joshjay05/SHEW",
    live: "https://shewfoundation.com/",
    organization: "Personal",
  },
  {
    title: "Itshekiri Association",
    description: "",
    id: "faq8",
    // date: "Ongoing",
    github: "https://github.com/Joshjay05/Association",
    live: "https://association-omega.vercel.app/",
    organization: "Personal",
  },
  {
    title: "Coffe Shop",
    description: "",
    id: "faq8",
    // date: "Ongoing",
    github: "https://github.com/Joshjay05/coffee-shop",
    live: "https://coffee-shop-orcin-gamma.vercel.app/",
    organization: "Personal",
  },
  {
    title: "e-commerce Admin Panel",
    description: "",
    id: "faq8",
    date: "Jan 2025",
    github: "",
    live: "",
    organization: "Switchive",
  },
  // {
  //   title: "Inventory",
  //   description: "",
  //   id: "faq8",
  //   date: "Ongoing",
  //   github: "https://github.com/Joshjay05/Inventory",
  //   live: "",
  //   organization: "Personal",
  // },
  // {
  //   title: "Auth",
  //   description: "",
  //   id: "faq8",
  //   date: "Ongoing",
  //   github: "https://github.com/Joshjay05/Auth",
  //   live: "",
  //   organization: "Personal",
  // },
  // https://twitter.com/JoshuaOdelade
];
